import assert from "node:assert/strict";
import { bandClass, directionalBasisLabel, directionalImpactClass, directionalImpactLabel, directionalPopupSurfaceClass, formatEventTypeLabel, impactScoreLabel, indiaImpactLabel, marketIntelPublicationLabel, marketIntelTimeLabel, marketTimingLabel, newsFreshnessLabel, sourceAgreementLabel, volatilityRiskClass, volatilitySellerNote, miMinimizeActive, MI_FILTERS, readMiFeedCache, writeMiFeedCache } from "./marketIntel.js";

assert.ok(MI_FILTERS.some((f) => f.id === "fed"));
assert.match(bandClass("CRITICAL"), /rose/);
assert.equal(/NIFTY|BANKNIFTY|SENSEX/.test(JSON.stringify(MI_FILTERS)), false);
assert.equal(impactScoreLabel(96), "Importance 96");
assert.equal(indiaImpactLabel(70), "Indian market impact 70");
assert.equal(directionalImpactLabel("SUPPORTIVE"), "Likely market up");
assert.equal(directionalImpactLabel("NEGATIVE"), "Likely market down");
assert.equal(directionalImpactLabel("MIXED", 0), "Mixed signals");
assert.equal(directionalImpactLabel("UNCLEAR", 0), "Market direction unclear");
assert.equal(directionalBasisLabel("HEADLINE"), "Direction read from headline.");
assert.equal(directionalBasisLabel("SUMMARY"), "Direction read from article summary; less direct than the headline.");
assert.equal(directionalBasisLabel("SOURCES"), "Direction checked against independent publisher reads.");
assert.equal(marketTimingLabel("AFTER_CLOSE"), "After market close");
assert.equal(newsFreshnessLabel("PUBLISH_TIME_UNKNOWN"), "Publisher time unavailable");
assert.equal(sourceAgreementLabel("DISAGREE"), "Independent reads disagree");
assert.match(volatilityRiskClass("HIGH"), /rose/);
assert.match(volatilitySellerNote("HIGH"), /review short-option exposure and hedges/);
assert.match(volatilitySellerNote("ELEVATED"), /review short-option exposure/);
assert.match(volatilitySellerNote("LOW"), /does not mean your positions are low risk/);
assert.equal(volatilitySellerNote("UNKNOWN"), null);
assert.match(marketIntelTimeLabel("2026-10-09T04:00:00Z"), /IST$/);
assert.equal(marketIntelPublicationLabel("2026-10-09T00:00:00Z", "DATE"), "2026-10-09");
assert.match(directionalImpactClass("SUPPORTIVE"), /emerald/);
assert.match(directionalImpactClass("NEGATIVE"), /rose/);
assert.match(directionalImpactClass("MIXED"), /amber/);
assert.match(directionalImpactClass("UNCLEAR"), /slate/);
assert.match(directionalPopupSurfaceClass("SUPPORTIVE"), /bg-emerald-50/);
assert.match(directionalPopupSurfaceClass("NEGATIVE"), /bg-rose-50/);
assert.match(directionalPopupSurfaceClass("MIXED"), /bg-amber-50/);
assert.match(directionalPopupSurfaceClass("UNCLEAR"), /bg-slate-50/);
assert.equal(formatEventTypeLabel("india_macro"), "INDIA MACRO");
assert.equal(formatEventTypeLabel("oil"), "OIL");
assert.equal(formatEventTypeLabel("fed-funds"), "FED FUNDS");
assert.equal(formatEventTypeLabel("geopolitics"), "GEOPOLITICS");
assert.equal(miMinimizeActive(100, 200), true);
assert.equal(miMinimizeActive(200, 200), false);
assert.equal(miMinimizeActive(201, 200), false);
writeMiFeedCache("2026-09-17", "all", [{ id: 1 }]);
assert.equal(readMiFeedCache("2026-09-17", "all").length, 1);
assert.equal(readMiFeedCache("2026-09-16", "all"), null);
console.log("marketIntel.test.js ok");
